Name: s3-end-point-without-aws-config-section
Description: Test CopyFile Handler
IsActive: true
Actions:
- Name: Action001
  Handler:
    Type: Synapse.Handlers.FileUtil:CopyFileHandler
    Config:
      Type: Yaml
      Values:
        Action: Copy
        OverwriteExisting: true
        Recurse : true
        PurgeDestination: false
        Verbose: true
  Parameters:
    Type: Yaml
    Values:
      FileSets:
      - Sources: 
        - s3://bucket/source/
        Destinations: 
        - c:\Destination1\