Name: SamplePlan
Actions:
- Name: Action001
  Handler:
    Type: synapse.handlers.Fileutil:MungeFileHandler
    Config: 
      Type: Yaml
      Values:
        Type: INI
        BackupSource: true
        CreateSettingIfNotFound: false
  Parameters:
    Values:
      Files:
      - Source: $WORKING_DIRECTORY\system.ini
        Destination: $WORKING_DIRECTORY\no-new-settings-system.ini.new
        SettingsFile:
          Name: $WORKING_DIRECTORY\initransform.csv
        Settings:
        - Key: TESTKEY
          Value: NEWTESTVALUE
        - Key: SECTION2
          Value: This is not a section
        - Key: "[NEWSECTION]:KEY"
          Value: Value for NEWSECTION:KEY
      - Source: $WORKING_DIRECTORY\config.properties
        Destination: $WORKING_DIRECTORY\no-new-settings-config.properties.new
        SettingsFile: 
          Name: $WORKING_DIRECTORY\kvptransform.csv
        Type: KeyValue
        Settings:
        - Key: color\=foreground
          Value: new color
        - Key: path
          Value: c:\\temp\\newpath\\doc1
      - Source: $WORKING_DIRECTORY\regex.config
        Destination: $WORKING_DIRECTORY\no-new-settings-regex.config.new
        SettingsFile: 
          Name: $WORKING_DIRECTORY\regextransform.csv
        Type: Regex
        Settings:
        - Key: (SET\s*ENDUR_VER\s*=\s*).*?$
          Value: ${1}NEW_VERSION_NUMBER_HERE
      - Source: $WORKING_DIRECTORY\xpath.config
        Destination: $WORKING_DIRECTORY\no-new-settings-xpath.config.new
        SettingsFile:
          Name: $WORKING_DIRECTORY\xpathtransform.csv
        Type: XPath
        Settings:
        - Key: "//configuration/applicationSettings/MyService.Properties.Settings/setting[@name=\"initVector\"]/value"
          Value: "MyNewValue"
      - Source: $WORKING_DIRECTORY\web.config
        Destination: $WORKING_DIRECTORY\no-new-settings-web.config.new
        SettingsFile:
          Name: $WORKING_DIRECTORY\xmltransform.xml
        Type: XmlTransform