Name: SamplePlan
Actions:
- Name: Action001
  Handler:
    Type: synapse.handlers.Fileutil:MungeFileHandler
    Config: 
      Type: Yaml
      Values:
        Type: INI
        BackupSource: true
        CreateSettingIfNotFound: true
  Parameters:
    Values:
      Files:
      - Source: s3://mybucket/dir/subdir/input.ini
        Destination: c:\temp\output.ini
        Settings:
        - Key: MyKey
          Value: MyValue
        - Key: MyKey2
          Value: MyValue2