Name: SamplePlan
Actions:
- Name: Action001
  Handler:
    Type: synapse.handlers.Fileutil:MungeFileHandler
    Config: 
      Type: Yaml
      Values:
        Type: INI
        BackupSource: true
        CreateSettingIfNotFound: true
  Parameters:
    Values:
      Files:
      - Source: $WORKING_DIRECTORY\system.ini
        Destination: $WORKING_DIRECTORY\without-settings-system.ini.new
        Settings:
        - Key: NewKey
          Value: NewValue
        - Key: TESTKEY
          Value: NEWTESTVALUE
        - Key: "[SECTION2]:string.1"
          Value: New Case 1
        - Key: SECTION2
          Value: This is not a section
        - Key: "[NEWSECTION]:KEY"
          Value: Value for NEWSECTION:KEY
      - Source: $WORKING_DIRECTORY\config.properties
        Destination: $WORKING_DIRECTORY\without-settings-config.properties.new
        Type: KeyValue
        Settings:
        - Key: NewKey
          Value: NewValue
        - Key: name
          Value: New\\Name
        - Key: color\=foreground
          Value: new color
        - Key: path
          Value: c:\\temp\\newpath\\doc1
      - Source: $WORKING_DIRECTORY\regex.config
        Destination: $WORKING_DIRECTORY\without-settings-regex.config.new
        Type: Regex
        Settings:
        - Key: (SET\s*ENDUR_VER\s*=\s*).*?$
          Value: ${1}NEW_VERSION_NUMBER_HERE
        - Key: (OLFCMD_URL\s*=\s*).*?$
          Value: ${1}http://newserver:1234
        - Key: (ENDUR_JRE\s*=\s*).*?$
          Value: ${1}jdk1.9.0.69
      - Source: $WORKING_DIRECTORY\xpath.config
        Destination: $WORKING_DIRECTORY\without-settings-xpath.config.new
        Type: XPath
        Settings:
        - Key: "//configuration/applicationSettings/MyService.Properties.Settings/setting[@name=\"initVector\"]/value"
          Value: "MyNewValue"
        - Key: "//configuration/applicationSettings/MyService.Properties.Settings/setting[@name=\"KeyContainerName\"]/value"
          Value: "NewKeyName"
